### ISSUE TITLE
automate zoom video recordings to youtube channel

### ISSUE THREAD

**Issue by danlopez00** [cdfoundation/foundation#188] opened 2020-05-13 18:40 UTC
automate uploads to youtube from zoom in k8s land you can see this https://github.com/kubernetes/community/blob/master/communication/youtube/youtube-guidelines.md#automation

**Comment by dnilasor** [comment] 2020-05-13 19:35
FWIW the "stream live on Youtube" feature in Zoom automates this natively without much work.

**Comment by jsalinas29** [comment] 2020-07-09 16:27
@markyjackson-taulia - i think this is a duplicate of 202

**Comment by markyjackson-taulia** [comment] 2020-07-09 16:28
Agreed, this is a dup

**Closed by jsalinas29** 2020-07-09 16:27 UTC

**Comment by markyjackson-taulia** [comment] 2020-07-09 16:29
I have completed this work as discussed and will pr the new zoom and YouTube guidelines in by the end of the week.
You rock @jsalinas29
