### ISSUE TITLE
Jenkins project would like to request a code signing certificate

### ISSUE THREAD

**Issue by caniszczyk** [cdfoundation/foundation#10] opened 2019-08-27 20:27 UTC
Jenkins project would like to request a code signing certificate for signing Jenkins releases. This is part of an initiative led by Olivier Vernin to remove single-points-of-failure from the current release process. I believe the certificate needs to be backed by a legal entity/organization.

**Comment by tracymiranda** [comment] 2019-09-09 13:25
Discussed briefly on 6 Sep - @danlopez00 could you please summarize what you shared & outline next steps, thanks.

**Comment by olblak** [comment] 2019-09-16 06:41
Hello any news with this?

**Comment by madchap** [comment] 2019-09-26 15:41
Hi, any news on this? :-)

**Comment by danlopez00** [comment] 2019-09-26 16:07
We have a path forward and I will update @tracymiranda and @kohsuke today. 

The summary:
 - Project will purchase and send invoice to LF/CDF via email address provided to @tracymiranda 
 - Not recommended that CDF and or LF sign the cert itself as an org, as that implies liability complexities not required for this
 - Jenkins project must remain signing org at this time

**Comment by caniszczyk** [comment] 2019-10-03 04:00
re-opening to get some more clarity on legal matters

**Comment by kohsuke** [comment] 2019-10-07 03:49
Every CA that I know issues code signing certificates to either individuals or legal entities, but never to something else, such as projects like Jenkins. AIU, this is by design.

Elsewhere, the standard practice is for a legal entity to acquire a code signing certificate, and then establish an internal operating policy to make sure the certificate doesn't get used to sign random stuff. This was certainly the case with all the companies I worked for. Projects like Firefox and Thunderbird sign their binaries with a code signing certificate issued to Mozilla (foundation or corporation, I forgot)

That's the only viable route that I can think of. IOW, Jenkins cannot acquire a signing cert. It needs to be the CDF, or some subsidiary thereof.

**Comment by danlopez00** [comment] 2019-10-18 20:28
**Update**: We are creating a new entity to support code signing and developer publishing. We will have another update once the LLC is created.

**Comment by danlopez00** [comment] 2019-11-01 14:44
@oleg-nenashev We had to establish a new legal entity to be able to handle this process. This took some time to get the legal/paperwork completed. I will checkin with our corp team today for update

**Comment by danlopez00** [comment] 2019-11-05 19:37
CDF Binary Project a Series of LF Projects, LLC is its formal name. CDF will setup service to be used for code signing

**Comment by danlopez00** [comment] 2019-11-12 20:08
DigiCert Account setup

![image](https://user-images.githubusercontent.com/727396/68706702-2a5f6a80-0545-11ea-9921-5a8ac7558e9a.png)

**Comment by danlopez00** [comment] 2019-11-12 20:18
@oleg-nenashev @kohsuke @olblak @madchap @tracymiranda 

Digicert should be fully operational today. Please send us an email at operations@cd.foundation with the following to be granted access:

```
First Name
Last Name
Email
Phone
Github username
Project Name
Company Name
```

**Comment by oleg-nenashev** [comment] 2019-11-12 20:24
Thanks! Should we also replace the personal code signing keys for Jenkins
componenta? I am using using one for few components in Jenkins, but I am
ready to switch to the CDF one and to update the developer guides to
reference the new process.

**Comment by madchap** [comment] 2019-11-12 21:08
Remoting should also switch.

**Comment by danlopez00** [comment] 2019-11-12 22:52
@oleg-nenashev @kohsuke @olblak @madchap @tracymiranda @caniszczyk 

Code Signing is now setup and is generally available.

**Comment by tracymiranda** [comment] 2019-11-13 14:29
Amazing, thanks @danlopez00

**Comment by oleg-nenashev** [comment] 2019-11-13 16:18
Thanks a lot for your help! Looks like we have resolved the major blocker for full automation of Jenkins releases, it is much appreciated

**Comment by olblak** [comment] 2019-11-19 09:57
@danlopez00 Have you received my email regarding a grant access? 
I sent it a week ago from olivier@vernin.me :)
Tell me if I missed something

**Comment by oleg-nenashev** [comment] 2019-11-19 10:02
Same for me. I applied 1 week ago, no reply so far. I assume everybody is
busy with Kubecon

**Comment by danlopez00** [comment] 2019-11-19 13:52
Hello all, thanks for patience on this one as it took a bit to get all the details (tech, legal, finance) squared away.

@olblak @oleg-nenashev and @madchap have been issued accounts and read/write API keys.

Closing ticket. Please dont hesitate to send an email to operations@cd.foundation for support

**Closed by danlopez00** 2019-11-19 13:52 UTC
Labels: high priority, operations

**Comment by olblak** [comment] 2019-11-19 16:49
To request a certificate, we need a credit card, any suggestion about the one that we should use? I am going to try to buy a code signing certificate in the coming days

**Comment by olblak** [comment] 2019-11-19 16:51
Thanks, @danlopez00 for this big milestone :fireworks:

**Comment by danlopez00** [comment] 2019-11-19 17:10
@olblak will send billing info over email

**Comment by olblak** [comment] 2019-12-11 09:45
I would like to reopen this issue as I can't request a code signing certificate.
I tried to request one with my own credit card, and my request staid pending for a little bit more than a week without further notification then I canceled when I discovered that I should use the CDF credit card but I can't use it either.
Could we plan a zoom session to move this issue forward?

**Comment by danlopez00** [comment] 2019-12-11 17:48
We should open a new ticket. This is really regarding Validation of the new Project Series LLC by Digicert.
